/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pojo.delta.common;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Details extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6246732225290295723L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Details\",\"namespace\":\"com.pojo.delta.common\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Details> ENCODER =
      new BinaryMessageEncoder<Details>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Details> DECODER =
      new BinaryMessageDecoder<Details>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Details> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Details> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Details> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Details>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Details to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Details from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Details instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Details fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }


  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Creates a new Details RecordBuilder.
   * @return A new Details RecordBuilder
   */
  public static com.pojo.delta.common.Details.Builder newBuilder() {
    return new com.pojo.delta.common.Details.Builder();
  }

  /**
   * Creates a new Details RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Details RecordBuilder
   */
  public static com.pojo.delta.common.Details.Builder newBuilder(com.pojo.delta.common.Details.Builder other) {
    if (other == null) {
      return new com.pojo.delta.common.Details.Builder();
    } else {
      return new com.pojo.delta.common.Details.Builder(other);
    }
  }

  /**
   * Creates a new Details RecordBuilder by copying an existing Details instance.
   * @param other The existing instance to copy.
   * @return A new Details RecordBuilder
   */
  public static com.pojo.delta.common.Details.Builder newBuilder(com.pojo.delta.common.Details other) {
    if (other == null) {
      return new com.pojo.delta.common.Details.Builder();
    } else {
      return new com.pojo.delta.common.Details.Builder(other);
    }
  }

  /**
   * RecordBuilder for Details instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Details>
    implements org.apache.avro.data.RecordBuilder<Details> {


    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pojo.delta.common.Details.Builder other) {
      super(other);
    }

    /**
     * Creates a Builder by copying an existing Details instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pojo.delta.common.Details other) {
      super(SCHEMA$);
    }

    @Override
    @SuppressWarnings("unchecked")
    public Details build() {
      try {
        Details record = new Details();
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Details>
    WRITER$ = (org.apache.avro.io.DatumWriter<Details>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Details>
    READER$ = (org.apache.avro.io.DatumReader<Details>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
    } else {
      for (int i = 0; i < 0; i++) {
        switch (fieldOrder[i].pos()) {
        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










