/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pojo.delta;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Universe extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4360596608500202459L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Universe\",\"namespace\":\"com.pojo.delta\",\"fields\":[{\"name\":\"numberOfPlanets\",\"type\":[\"null\",{\"type\":\"long\",\"java-class\":\"java.lang.Long\"}]},{\"name\":\"planets\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Planet\",\"fields\":[{\"name\":\"details\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Details\",\"namespace\":\"com.pojo.delta.common\",\"fields\":[]}]},{\"name\":\"distanceFromSun\",\"type\":[\"null\",{\"type\":\"long\",\"java-class\":\"java.lang.Long\"}]},{\"name\":\"numberOfMoons\",\"type\":[\"null\",{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}]},{\"name\":\"planetName\",\"type\":[\"null\",\"string\"]},{\"name\":\"planetSize\",\"type\":[\"null\",\"string\"]}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Universe> ENCODER =
      new BinaryMessageEncoder<Universe>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Universe> DECODER =
      new BinaryMessageDecoder<Universe>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Universe> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Universe> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Universe> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Universe>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Universe to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Universe from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Universe instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Universe fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long numberOfPlanets;
   private java.util.List<com.pojo.delta.Planet> planets;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Universe() {}

  /**
   * All-args constructor.
   * @param numberOfPlanets The new value for numberOfPlanets
   * @param planets The new value for planets
   */
  public Universe(java.lang.Long numberOfPlanets, java.util.List<com.pojo.delta.Planet> planets) {
    this.numberOfPlanets = numberOfPlanets;
    this.planets = planets;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return numberOfPlanets;
    case 1: return planets;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: numberOfPlanets = (java.lang.Long)value$; break;
    case 1: planets = (java.util.List<com.pojo.delta.Planet>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'numberOfPlanets' field.
   * @return The value of the 'numberOfPlanets' field.
   */
  public java.lang.Long getNumberOfPlanets() {
    return numberOfPlanets;
  }


  /**
   * Sets the value of the 'numberOfPlanets' field.
   * @param value the value to set.
   */
  public void setNumberOfPlanets(java.lang.Long value) {
    this.numberOfPlanets = value;
  }

  /**
   * Gets the value of the 'planets' field.
   * @return The value of the 'planets' field.
   */
  public java.util.List<com.pojo.delta.Planet> getPlanets() {
    return planets;
  }


  /**
   * Sets the value of the 'planets' field.
   * @param value the value to set.
   */
  public void setPlanets(java.util.List<com.pojo.delta.Planet> value) {
    this.planets = value;
  }

  /**
   * Creates a new Universe RecordBuilder.
   * @return A new Universe RecordBuilder
   */
  public static com.pojo.delta.Universe.Builder newBuilder() {
    return new com.pojo.delta.Universe.Builder();
  }

  /**
   * Creates a new Universe RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Universe RecordBuilder
   */
  public static com.pojo.delta.Universe.Builder newBuilder(com.pojo.delta.Universe.Builder other) {
    if (other == null) {
      return new com.pojo.delta.Universe.Builder();
    } else {
      return new com.pojo.delta.Universe.Builder(other);
    }
  }

  /**
   * Creates a new Universe RecordBuilder by copying an existing Universe instance.
   * @param other The existing instance to copy.
   * @return A new Universe RecordBuilder
   */
  public static com.pojo.delta.Universe.Builder newBuilder(com.pojo.delta.Universe other) {
    if (other == null) {
      return new com.pojo.delta.Universe.Builder();
    } else {
      return new com.pojo.delta.Universe.Builder(other);
    }
  }

  /**
   * RecordBuilder for Universe instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Universe>
    implements org.apache.avro.data.RecordBuilder<Universe> {

    private java.lang.Long numberOfPlanets;
    private java.util.List<com.pojo.delta.Planet> planets;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pojo.delta.Universe.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.numberOfPlanets)) {
        this.numberOfPlanets = data().deepCopy(fields()[0].schema(), other.numberOfPlanets);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.planets)) {
        this.planets = data().deepCopy(fields()[1].schema(), other.planets);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Universe instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pojo.delta.Universe other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.numberOfPlanets)) {
        this.numberOfPlanets = data().deepCopy(fields()[0].schema(), other.numberOfPlanets);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.planets)) {
        this.planets = data().deepCopy(fields()[1].schema(), other.planets);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'numberOfPlanets' field.
      * @return The value.
      */
    public java.lang.Long getNumberOfPlanets() {
      return numberOfPlanets;
    }


    /**
      * Sets the value of the 'numberOfPlanets' field.
      * @param value The value of 'numberOfPlanets'.
      * @return This builder.
      */
    public com.pojo.delta.Universe.Builder setNumberOfPlanets(java.lang.Long value) {
      validate(fields()[0], value);
      this.numberOfPlanets = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'numberOfPlanets' field has been set.
      * @return True if the 'numberOfPlanets' field has been set, false otherwise.
      */
    public boolean hasNumberOfPlanets() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'numberOfPlanets' field.
      * @return This builder.
      */
    public com.pojo.delta.Universe.Builder clearNumberOfPlanets() {
      numberOfPlanets = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'planets' field.
      * @return The value.
      */
    public java.util.List<com.pojo.delta.Planet> getPlanets() {
      return planets;
    }


    /**
      * Sets the value of the 'planets' field.
      * @param value The value of 'planets'.
      * @return This builder.
      */
    public com.pojo.delta.Universe.Builder setPlanets(java.util.List<com.pojo.delta.Planet> value) {
      validate(fields()[1], value);
      this.planets = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'planets' field has been set.
      * @return True if the 'planets' field has been set, false otherwise.
      */
    public boolean hasPlanets() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'planets' field.
      * @return This builder.
      */
    public com.pojo.delta.Universe.Builder clearPlanets() {
      planets = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Universe build() {
      try {
        Universe record = new Universe();
        record.numberOfPlanets = fieldSetFlags()[0] ? this.numberOfPlanets : (java.lang.Long) defaultValue(fields()[0]);
        record.planets = fieldSetFlags()[1] ? this.planets : (java.util.List<com.pojo.delta.Planet>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Universe>
    WRITER$ = (org.apache.avro.io.DatumWriter<Universe>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Universe>
    READER$ = (org.apache.avro.io.DatumReader<Universe>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.numberOfPlanets == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.numberOfPlanets);
    }

    if (this.planets == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.planets.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (com.pojo.delta.Planet e0: this.planets) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.numberOfPlanets = null;
      } else {
        this.numberOfPlanets = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.planets = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<com.pojo.delta.Planet> a0 = this.planets;
        if (a0 == null) {
          a0 = new SpecificData.Array<com.pojo.delta.Planet>((int)size0, SCHEMA$.getField("planets").schema().getTypes().get(1));
          this.planets = a0;
        } else a0.clear();
        SpecificData.Array<com.pojo.delta.Planet> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.pojo.delta.Planet>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            com.pojo.delta.Planet e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new com.pojo.delta.Planet();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.numberOfPlanets = null;
          } else {
            this.numberOfPlanets = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.planets = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<com.pojo.delta.Planet> a0 = this.planets;
            if (a0 == null) {
              a0 = new SpecificData.Array<com.pojo.delta.Planet>((int)size0, SCHEMA$.getField("planets").schema().getTypes().get(1));
              this.planets = a0;
            } else a0.clear();
            SpecificData.Array<com.pojo.delta.Planet> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.pojo.delta.Planet>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                com.pojo.delta.Planet e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new com.pojo.delta.Planet();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










